# Generated by Django 5.0.2 on 2025-05-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_color_faq_storage_remove_product_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorimage',
            options={'verbose_name': 'Color Image', 'verbose_name_plural': 'Color Images'},
        ),
    ]
