# Generated by Django 5.0.2 on 2025-06-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_colorimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='model',
        ),
    ]
