# Generated by Django 5.0.2 on 2025-06-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_image_options_rename_title_product_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='title',
        ),
    ]
