# Generated by Django 5.0.2 on 2025-06-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_model_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='model',
        ),
    ]
